<?php

namespace EventIUT\SalonsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateSalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateSalonRepository extends EntityRepository
{
}
