<?php

namespace prostage\ProstageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * entrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrepriseRepository extends EntityRepository
{
}
